name: Production Monitoring

on:
  workflow_dispatch: # Put here!!
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: |
          python main.py

      - name: Upload downtime artifact
        if: success() && always()
        run: echo "DOWNTIME=$(cat downtime.txt)" > downtime.env
        shell: bash

      - name: Upload Downtime Artifact
        if: success() && always()
        uses: actions/upload-artifact@v2
        with:
          name: downtime-artifact
          path: downtime.env
