name: Production Monitoring

on:
  workflow_dispatch: # Put here!!
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: |
          python main.py

